# Generated by Django 5.0.6 on 2026-08-27 08:24

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_savedsearch_searchhistory_job_search_vector_and_more"),
        ("recruiters", "0001_initial"),
        ("seekers", "0004_seekerprofile_hide_current_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterCredits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monthly_reveal_limit", models.PositiveSmallIntegerField(default=0)),
                (
                    "reveals_used_this_month",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cycle_starts_on", models.DateField(default=datetime.date.today)),
                (
                    "recruiter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Recruiter credits",
                "db_table": "recruiter_credits",
            },
        ),
        migrations.CreateModel(
            name="CandidateView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_kind",
                    models.CharField(
                        choices=[
                            ("search_result", "Search Result"),
                            ("detail", "Detail View"),
                            ("saved_list", "Saved Candidates List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_revealed", models.BooleanField(default=False)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_views",
                        to="recruiters.recruiterprofile",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views",
                        to="seekers.seekerprofile",
                    ),
                ),
                (
                    "target_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job the recruiter was searching for, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_views",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recruiter", "-created_at"],
                        name="candidate_v_recruit_1fc6bd_idx",
                    ),
                    models.Index(
                        fields=["seeker", "-created_at"],
                        name="candidate_v_seeker__a46ebc_idx",
                    ),
                    models.Index(
                        fields=["contact_revealed", "-revealed_at"],
                        name="candidate_v_contact_6cc522_idx",
                    ),
                    models.Index(
                        fields=["recruiter", "seeker", "contact_revealed"],
                        name="candidate_v_recruit_385411_idx",
                    ),
                ],
            },
        ),
    ]
