# Generated by Django 5.0.6 on 2026-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_twofactorauth_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Why the user closed their account. Optional, self-reported.', max_length=500),
        ),
    ]
