# Generated by Django 5.0.6 on 2026-08-14 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_tags',
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='jobs.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('min_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('max_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('work_arrangement', models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='on_site', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=3)),
                ('salary_period', models.CharField(choices=[('monthly', 'Per Month'), ('yearly', 'Per Year')], default='yearly', max_length=20)),
                ('is_salary_negotiable', models.BooleanField(default=False)),
                ('is_salary_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='recruiters.company')),
                ('nice_to_have_skills', models.ManyToManyField(blank=True, related_name='nice_to_have_for_jobs', to='skills.skill')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_jobs', to='recruiters.recruiterprofile')),
                ('required_skills', models.ManyToManyField(related_name='required_for_jobs', to='skills.skill')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.jobcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.tag')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-activated_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_deleted', '-activated_at'], name='jobs_status_8129b2_idx'), models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'), models.Index(fields=['category', 'status'], name='jobs_categor_1a990f_idx')],
            },
        ),
    ]
