# Generated by Django 5.2.17 on 2026-09-10 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable identifier the award checker matches on.', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('profile', 'Profile'), ('skills', 'Skills'), ('applications', 'Applications'), ('learning', 'Learning'), ('community', 'Community')], max_length=20)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=10, help_text='Points awarded on earning this badge.')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['category', 'sort_order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_weeks', models.PositiveIntegerField(default=0)),
                ('longest_weeks', models.PositiveIntegerField(default=0)),
                ('last_active_week', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_streaks',
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'earned_badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='earned_badg_user_id_cc6a4d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='one_badge_per_user')],
            },
        ),
        migrations.CreateModel(
            name='PerkRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perk', models.CharField(choices=[('match_score_day', 'Match scores for 24 hours'), ('skill_gap_day', 'Skill gap report for 24 hours')], max_length=30)),
                ('points_spent', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perk_redemptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'perk', '-expires_at'], name='perk_redemp_user_id_149f4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('badge', 'Badge earned'), ('goal', 'Weekly goal met'), ('streak', 'Streak milestone'), ('redemption', 'Spent on a perk'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='points_ledg_user_id_ef075d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('applications', 'Applications sent'), ('skills', 'Skills added'), ('courses', 'Courses started')], max_length=20)),
                ('target', models.PositiveSmallIntegerField()),
                ('week_start', models.DateField(help_text='Monday of the week this covers.')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_goals',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['user', '-week_start'], name='weekly_goal_user_id_6d311b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'week_start'), name='one_goal_per_kind_per_week')],
            },
        ),
    ]
