# Generated by Django 5.0.6 on 2026-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_ats_breakdown_resume_ats_score_resumeskill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="advanced_ats_analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="advanced_ats_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resume",
            name="advanced_ats_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Advanced ATS score, normalized to 0-100",
                null=True,
            ),
        ),
    ]
