# Generated by Django 5.2.17 on 2026-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_advanced_ats_analyzed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="advanced_ats_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
