# Generated by Django 5.0.6 on 2026-08-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_savedsearch_searchhistory_job_search_vector_and_more"),
        ("recruiters", "0001_initial"),
        ("seekers", "0003_alter_seekerprofile_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overall_score", models.FloatField(db_index=True)),
                ("skills_score", models.FloatField()),
                ("experience_score", models.FloatField()),
                ("location_score", models.FloatField()),
                ("salary_score", models.FloatField()),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="jobs.job",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_scores",
                "indexes": [
                    models.Index(
                        fields=["seeker", "-overall_score"],
                        name="match_score_seeker__b68625_idx",
                    ),
                    models.Index(
                        fields=["job", "-overall_score"],
                        name="match_score_job_id_fa3d67_idx",
                    ),
                    models.Index(
                        fields=["-overall_score", "-computed_at"],
                        name="match_score_overall_41978d_idx",
                    ),
                ],
                "unique_together": {("seeker", "job")},
            },
        ),
        migrations.CreateModel(
            name="SavedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_candidates",
                        to="recruiters.recruiterprofile",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "saved_candidates",
                "ordering": ["-created_at"],
                "unique_together": {("recruiter", "seeker")},
            },
        ),
    ]
