# Generated by Django 5.0.6 on 2026-09-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_plan_has_advanced_filters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this refund was issued. Required for accountability.",
                        max_length=500,
                    ),
                ),
                (
                    "access_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the paid subscription was ended alongside this refund.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending at gateway"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who authorised the refund. Null for system refunds.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "refunds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction", "-created_at"],
                        name="refunds_transac_1b2ed6_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="refunds_status_318f0e_idx",
                    ),
                ],
            },
        ),
    ]
