# Generated by Django 5.0.6 on 2026-08-14 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_savedsearch_searchhistory_job_search_vector_and_more'),
        ('seekers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, max_length=2000)),
                ('resume_url', models.URLField(blank=True, help_text='Link to online resume (Drive, GitHub, etc.). Phase 2 mein resume upload aayega.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('recruiter_notes', models.TextField(blank=True, max_length=2000)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_status_change_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='seekers.seekerprofile')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status', 'is_deleted'], name='application_job_id_16dd11_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['seeker', '-submitted_at'], name='application_seeker__3d6e31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('seeker', 'job')},
        ),
    ]
