# Generated by Django 5.0.6 on 2026-09-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_unique_together_and_more'),
        ('resumes', '0003_resume_advanced_ats_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, help_text="The uploaded resume sent with this application. Defaults to the seeker's primary resume at submission time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, help_text='Optional external resume link (Drive, GitHub, personal site) for seekers who have not uploaded a file.'),
        ),
    ]
