# Generated by Django 5.1.15 on 2026-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_resume_alter_application_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20),
        ),
    ]
