# Generated by Django 5.0.6 on 2026-08-15 18:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekerprofile",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
