# Generated by Django 5.0.6 on 2026-08-15 18:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0002_seekerprofile_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekerprofile",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
