# Generated by Django 5.0.6 on 2026-08-25 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seekers', '0003_alter_seekerprofile_public_id'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('data', 'Data & ML'), ('design', 'Design'), ('product', 'Product'), ('business', 'Business'), ('operations', 'Operations'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('min_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('typical_experience_years', models.PositiveSmallIntegerField(default=3)),
                ('avg_salary_inr', models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary in INR', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Target Role',
                'verbose_name_plural': 'Target Roles',
                'db_table': 'target_roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TargetRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance', models.CharField(choices=[('critical', 'Critical (must have)'), ('important', 'Important (strongly preferred)'), ('preferred', 'Preferred (bonus)'), ('optional', 'Optional (nice to have)')], default='important', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (1-2 weeks)'), ('medium', 'Medium (1-2 months)'), ('hard', 'Hard (3+ months)')], default='medium', max_length=20)),
                ('rationale', models.CharField(blank=True, max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_role_skills', to='skills.skill')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_role_skills', to='career_intel.targetrole')),
            ],
            options={
                'verbose_name': 'Target Role Skill',
                'verbose_name_plural': 'Target Role Skills',
                'db_table': 'target_role_skills',
                'ordering': ['-importance', 'skill__name'],
                'unique_together': {('target_role', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='targetrole',
            name='skills',
            field=models.ManyToManyField(related_name='target_roles', through='career_intel.TargetRoleSkill', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='SkillGapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gap_score', models.FloatField(db_index=True)),
                ('total_required_skills', models.PositiveSmallIntegerField()),
                ('matched_count', models.PositiveSmallIntegerField()),
                ('missing_critical_count', models.PositiveSmallIntegerField()),
                ('missing_important_count', models.PositiveSmallIntegerField()),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_snapshots', to='seekers.seekerprofile')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='career_intel.targetrole')),
            ],
            options={
                'verbose_name': 'Skill Gap Snapshot',
                'verbose_name_plural': 'Skill Gap Snapshots',
                'db_table': 'skill_gap_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seeker', '-created_at'], name='skill_gap_s_seeker__2dd04d_idx'), models.Index(fields=['seeker', 'target_role', '-created_at'], name='skill_gap_s_seeker__0c23a0_idx')],
            },
        ),
    ]
