# Generated by Django 5.0.6 on 2026-08-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_intel", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("logo_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "trust_score",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="0-10. Coursera/edX = 9, generic blog = 3"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Learning Provider",
                "verbose_name_plural": "Learning Providers",
                "db_table": "learning_providers",
                "ordering": ["-trust_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("url", models.URLField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("course", "Video Course"),
                            ("book", "Book"),
                            ("article", "Article"),
                            ("documentation", "Documentation"),
                            ("tutorial", "Tutorial Series"),
                            ("bootcamp", "Bootcamp"),
                            ("project", "Hands-on Project"),
                            ("certification", "Certification"),
                            ("video", "Single Video"),
                            ("podcast", "Podcast"),
                        ],
                        default="course",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Approximate hours needed to complete",
                        null=True,
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "price_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "external_rating",
                    models.FloatField(
                        blank=True,
                        help_text="Rating on the external platform (0-5)",
                        null=True,
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Internal computed score (0-100)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_endorsed",
                    models.BooleanField(
                        default=False, help_text="Highly recommended by the curator"
                    ),
                ),
                ("enrollment_count", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="career_intel.learningprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Resource",
                "verbose_name_plural": "Learning Resources",
                "db_table": "learning_resources",
                "ordering": ["-is_endorsed", "-quality_score", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResourceSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the main skill the resource teaches?",
                    ),
                ),
                (
                    "coverage",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="How thoroughly the skill is covered (0-100).",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_skills",
                        to="career_intel.learningresource",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_skills",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Skill",
                "verbose_name_plural": "Resource Skills",
                "db_table": "resource_skills",
                "ordering": ["-is_primary", "-coverage"],
                "unique_together": {("resource", "skill")},
            },
        ),
        migrations.AddField(
            model_name="learningresource",
            name="skills",
            field=models.ManyToManyField(
                related_name="learning_resources",
                through="career_intel.ResourceSkill",
                to="skills.skill",
            ),
        ),
        migrations.CreateModel(
            name="UserLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_learn", "Want to Learn"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="want_to_learn",
                        max_length=20,
                    ),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Completion percentage (0-100)"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The user's own rating, 1-5 stars",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1000)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_learnings",
                        to="career_intel.learningresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Learning",
                "verbose_name_plural": "User Learnings",
                "db_table": "user_learnings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["kind", "difficulty", "is_active"],
                name="learning_re_kind_85dbd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["-quality_score", "-is_endorsed"],
                name="learning_re_quality_58bc8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userlearning",
            index=models.Index(
                fields=["user", "status"], name="user_learni_user_id_d59090_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlearning",
            unique_together={("user", "resource")},
        ),
    ]
