# Generated by Django 5.0.6 on 2026-08-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_intel', '0003_salarysubmission'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('level', models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Junior'), (3, 'Mid-level'), (4, 'Senior'), (5, 'Lead/Principal'), (6, 'Executive')], default=3)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('data', 'Data & ML'), ('design', 'Design'), ('product', 'Product'), ('business', 'Business'), ('operations', 'Operations'), ('other', 'Other')], default='other', max_length=30)),
                ('typical_experience_years', models.PositiveSmallIntegerField(default=3)),
                ('avg_salary_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_nodes', to='career_intel.targetrole')),
            ],
            options={
                'db_table': 'career_path_nodes',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPathEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='Difficulty: 1 = easy, 10 = very hard')),
                ('time_months', models.PositiveSmallIntegerField(default=12, help_text='Typical time needed to make this transition')),
                ('transition_type', models.CharField(choices=[('vertical', 'Vertical (promotion)'), ('lateral', 'Lateral (same level)'), ('leap', 'Leap (skip levels)'), ('pivot', 'Pivot (different category)')], default='vertical', max_length=20)),
                ('rationale', models.TextField(blank=True, help_text='Why this is a common or valid transition', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='career_transitions', to='skills.skill')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='career_intel.careerpathnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='career_intel.careerpathnode')),
            ],
            options={
                'db_table': 'career_path_edges',
                'ordering': ['weight'],
            },
        ),
        migrations.AddIndex(
            model_name='careerpathnode',
            index=models.Index(fields=['category', 'level'], name='career_path_categor_a698f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careerpathedge',
            unique_together={('from_node', 'to_node')},
        ),
    ]
