# Generated by Django 5.0.6 on 2026-08-21 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_application_updates', models.BooleanField(default=True)),
                ('email_new_matches_digest', models.BooleanField(default=True)),
                ('email_payment_events', models.BooleanField(default=True)),
                ('email_subscription_alerts', models.BooleanField(default=True)),
                ('email_profile_views', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8)),
                ('unsubscribe_token', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('application_received', 'Application Received (Recruiter)'), ('app_status_change', 'Application Status Changed (Seeker)'), ('app_withdrawn', 'Application Withdrawn (Recruiter)'), ('new_matching_job', 'New Matching Job (Seeker)'), ('new_matching_candidate', 'New Matching Candidate (Recruiter)'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('sub_expiring', 'Subscription Expiring Soon'), ('sub_expired', 'Subscription Expired'), ('profile_viewed', 'Profile Viewed (Seeker)'), ('job_approved', 'Job Approved (Recruiter)'), ('job_rejected', 'Job Rejected (Recruiter)')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_priority', models.CharField(choices=[('instant', 'Instant'), ('digest', 'Daily Digest'), ('none', 'In-App Only')], default='instant', max_length=20)),
                ('is_emailed', models.BooleanField(db_index=True, default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_failure', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['delivery_priority', 'is_emailed'], name='notificatio_deliver_fd07cd_idx')],
            },
        ),
    ]
