# Generated by Django 5.0.6 on 2026-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="push_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
